### ISSUE TITLE
BUG: Partial unselectability when using modded elements.

### ISSUE THREAD

**Issue by Xyrmes** [SpencerMycek/KineticistExpandedElements#56] opened 2022-10-04 02:19 UTC
So, when I make a kineticist that uses any of the new elements, and then restart the game, they appear naked and can only be selected via their portrait. This only seems to begin after exiting the game and then returning to it.

I've seen this happen with another mod, _Homebrew Archetypes_ (https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/279), but I removed it after Enhanced Edition was released due to it being implemented via template and not UMM; this bug with Kineticists also existed then. Classes added via other mods, such as Antipaladin from _Microscopic Content Expansion_ (https://github.com/alterasc/MicroscopicContentExpansion), do not seem to be affected.

Seeing as I have not seen this bug posted here, I am assuming it's either rare, or due to some niche interaction between mods I have installed. I have done a removal and clean reinstall of all my mods, and this didn't clear up the issue.

![Problem pt5](https://user-images.githubusercontent.com/31435121/193720087-98a618ac-795f-45a2-8e44-ffbce6b1e78e.png)
<img width="1136" alt="Problem pt1" src="https://user-images.githubusercontent.com/31435121/193720102-b5ba9906-0ea6-4bc1-8914-458b61011b9a.png">
![Problem pt2](https://user-images.githubusercontent.com/31435121/193720110-b7a3795c-9bbe-4cbb-8c12-66af9a584a2b.png)
![Problem pt3](https://user-images.githubusercontent.com/31435121/193720121-5246770a-3c64-4cac-a72b-94247e1dac2a.png)
<img width="1621" alt="Problem pt4" src="https://user-images.githubusercontent.com/31435121/193720386-631f035e-aaf3-4cab-9c29-32944e900e1d.png">

I hope this is enough information.

**Comment by Brownt65** [comment] 2022-10-04 21:41
Have you tried restarting the game? I had the same issue but saving and reloading fixed it for me?

**Comment by Xyrmes** [comment] 2022-10-05 00:30
> Have you tried restarting the game? I had the same issue but saving and reloading fixed it for me?

I have, and it doesn't help. I did happen on a strange instance where I replaced the kineticist with someone else and then swapped them back, and she was targetable, but I can't remember if I saved/loaded in between. I tried to swap them via Toybox, but that only made the kineticist stand like a statue when she moved until a fight happened.

**Comment by SpencerMycek** [comment] 2022-10-05 11:42
Oh my god I thought it was just me
I have no idea what causes the issue, but it's happened to me a ton (to fix it I just fully respec using Toybox)

No Idea what the issue is. I wish I knew what caused it

What archetypes/elements/blades are you using?

**Comment by Xyrmes** [comment] 2022-10-05 15:39
> What archetypes/elements/blades are you using?

I went with Dark Elementalist and Void/Negative this time, but I've also seen this with Psychokineticist and Void/Gravity before.
*edited for spelling

**Comment by Brownt65** [comment] 2022-10-05 18:03
Hmm is this happening when you select void or any of the new elements?

**Comment by Xyrmes** [comment] 2022-10-05 20:54
I haven't tested every one of them. But it happens when I select void and either negative or gravity, and I think I did it months ago with aether and it also happened.

**Comment by Brownt65** [comment] 2022-10-07 22:29
Ok I figured out what's causing the issue. Whenever you use the kinetic blade it causing some type issue not sure what but if you unsummon it save and reload it fixes the issue. No respecting necessary.

**Comment by Xyrmes** [comment] 2022-10-08 01:56
So it's the blade and not the element? Well, that's manageable.

**Comment by Brownt65** [comment] 2022-10-08 05:57
After testing with both void and aether I've discovered that you can use the blade just fine but just unsummon it before you save and you shouldn't have a problem. It's an annoying bug but a very manageable one until it's fixed.

**Comment by SpencerMycek** [comment] 2022-10-12 12:01
Yeah, I've found the kinetic blades can be very fiddly
I'll look into what I'm doing differently than the vanilla blades and see if I can fix this issue

**Comment by SpencerMycek** [comment] 2022-10-14 11:04
Fixed in v3.0.1

**Closed as completed by SpencerMycek** 2022-10-14 11:04 UTC
