### ISSUE TITLE
Fix and Bug Suggestions

### ISSUE THREAD

**Issue by ebonfowl** [SpencerMycek/KineticistExpandedElements#87] opened 2024-06-14 15:15 UTC
I noticed a few things while using elements of your mod. I'm running a few other mods that impact Kineticist (Dark Codex and Kinetic Archetypes), so I am unsure whether it is an interaction thing.

1) I know this has been reported a bunch, but Vampiric Infusion doesn't make Void Healer free. Looking at your code, you might consider changing `RemoveBuffOnAcceptBurn` to false. The vampiric infusion from the blood kineticist does not have this set to true, nor does any other instance of burn reduction I have seen across any mod or vanilla blueprint. I'm not sure why it is there anyway, as `Action = Helper.CreateActionList(new ContextActionRemoveSelf {})` is the thing that actually removes the buff when you use Void Healer.

2) No matter how I use it, Void Blast only does half damage. I don't mean that each damage instance (bludgeoning and negative) each do half the dice damage like any other physical/energy composite, I mean that there is a x0.5 multiplier applied to _each_ damage instance. Void kinetic blade, blast, extended range - all are half damage. Negative and gravity both work fine on their own.

3) All the added kinetic blades cost nothing. I can walk and use a composite kinetic blade with no cost in burn.

4) Forgot one more: the cost of Greater Gravitic Boost is incorrect. It should only add 1 `KineticistBurnType.Blast`, not 3. I think the confusion originates from this clause in the Gravitic Boost description: "At 15th level, you can also infuse a composite blast with gravity, though to do so you must accept 1 additional point of burn." This additional burn is intended to be added to the cost of the composite blast, not _on top_ of the 2 extra burn you would normally incur for applying Gravitic Boost to a simple physical blast. This is clarified by Mark Seifter from Paizo [here](https://paizo.com/threads/rzs2tk0l?How-much-burn-does-an-Gravitic-Boost).

**Comment by SpencerMycek** [comment] 2024-06-14 17:41
1. Going to work on this, Vampiric Infusion makes me unhappy
2. Screenshots are not working for me, currently. But, I just tested this, At level 7 simple blasts do 4d6, while composites do 8d6. Void Blast does 8d6 * (0.5) for both Negative and Physical, meaning it is doing the whole 8d6. This is inline with my other energy/physical composites, like wood's summer blast, and identical to how the base game's blast works (I tested with Charged Water Blast)

This may still be wrong, but all of the composite blasts work similarly. I've tested Void, other modded composites (Summer), and vanilla (although Dark Codex and ToyBox are installed). They all work this way, and in testing I've found their damage lines up with non-mixed type composites. Please let me know if I'm wrong here, or provide a screenshot

3. Should be fixed in the next update, thank you!
4. Oh man, that makes it so much better, I thought it was still worth it to make composite blast die steps increase, but now it's not prohibitively expensive. Thank you!

**Comment by ebonfowl** [comment] 2024-06-14 19:23
EDIT: I re-read your post - it seems like this is a problem on my end then with the composite blasts since yours are working as intended. Perhaps mod-related.

Wow, thanks for the quick reply! So upon further testing, I think I figured out the problem with the composite blasts. Looks like when I add magma blast via Toolbox it still applies the x0.5 modifier to the damage, _but_ the damage starts doubled. That is, _full composite damage for both damage components_ (bludgeoning and fire) which then get reduced by half to yield the proper amount of damage. This is, why I assume the mixed physical/energy blasts show up incorrectly on the character sheet. I thought it was so cool that you figure out how to make your composite physical/energy blasts show up correctly on the character sheet, but now I realize they probably have to show up incorrectly to work right. :)

I also tested summer blast (I think that is the name - wood/fire) and autumn blast (wood/earth) and they both do half damage too. So, I think the issue is that the initial damage dice need to be doubled for all composite blasts, then the game will make them correct. Ironically, the one composite that does proper damage is force blast since it is supposed to do half damage.

![image](https://github.com/SpencerMycek/KineticistExpandedElements/assets/101683149/436fc868-1477-4fe0-856d-1d13b085e434)

Hopefully that screenshot pasted in correctly. The huge number of blast dice come from Legend mythic and the unlocked class from Dark Codex if that looks odd.

And I agree, I love vampiric infusion too and even at 1 composite burn, gravitic is overpriced for what you get (compared to something like empowered metakinesis), but at least at 1 it is affordable and situationally useful.

**Comment by SpencerMycek** [comment] 2024-06-14 19:57
Everything you show makes sense, but do you have other mods installed?

Here is one half of Magma Blast, for me:
![image](https://github.com/SpencerMycek/KineticistExpandedElements/assets/32203066/0f90bcfa-6c49-4f98-8ce1-2f077b13e49f)
And one half of void blast:
![image](https://github.com/SpencerMycek/KineticistExpandedElements/assets/32203066/653d5a7d-5b98-43a7-80da-b2dc0dc2a24c)

Let me try to figure out the math here:
At level 10 (my photos) You should have a 5d6 normal blast and a 10d6 composite
At level 20 (your photos) you should have a 10d6 normal blast and a 20d6 composite
Your photos also show a base of 40d6 for composites, which would imply a 20d6 simple blast

I think the issue is the unlocked class thing, although I'm not sure why

If we assume that your base normal blast is 20d6 (composite 40d6), then yes 40d6 * 1/2 is correct (for split damage)
If we assume that your base normal blast is 10d6 (composite 20d6), then 20d6 * 1/2 is correct

**Comment by ebonfowl** [comment] 2024-06-14 21:05
Yep, yours is correct. Issue is on my end.

For reference, my character is level 40 (Legend mythic path) with 20 base blast dice. So the simple blasts should be 20 and the composites should be 40.

I don't think its the unlocked class thing. I tested a level 20 and level 11 base kineticist too and see the same thing. I mean, unless it fundamentally changes the way blast dice progression works, but I looked at the code and it appears to just add entries for levels above 20 in a loop. I'm going to spend more time on it, but this appears to be a me problem. ;)

**Comment by SpencerMycek** [comment] 2024-06-14 21:11
Dark Codex and KEE are fairly close in how they handle things (I use CodexLib, which is the library part of DarkCodex)
The one place we might differ is how blasts are created/modified, so Dark Codex might just unlock the maximum die amount, while KEE does not

I'll try and look into it

**Comment by SpencerMycek** [comment] 2024-06-14 21:13
On the plus side, I've just fixed vampiric infusion

**Comment by ebonfowl** [comment] 2024-06-14 23:02
> Dark Codex and KEE are fairly close in how they handle things (I use CodexLib, which is the library part of DarkCodex) The one place we might differ is how blasts are created/modified, so Dark Codex might just unlock the maximum die amount, while KEE does not
> 
> I'll try and look into it

You don't need to solve my problems for me, but I appreciate it! I had the same thought about the capping issue, but as I test it further it is happening for the added blasts even at low levels where capping can't matter.

> On the plus side, I've just fixed vampiric infusion

NICE! What ended up being the issue?

**Comment by SpencerMycek** [comment] 2024-06-15 03:38
Uhhhh, a mixture of not correctly telling the infusion what abilities it worked off of and affected (void/negative and void healer)
And that one thing you mentioned originally. Not sure which one fixed the lag, but who knows

**Closed as completed** 2024-06-16 16:52 UTC
