### ISSUE TITLE
Wood (and Composites)  blast blade causing doll errors

### ISSUE THREAD

**Issue by bittercranberry** [SpencerMycek/KineticistExpandedElements#54] opened 2022-10-02 16:30 UTC
The item used as the blade for wood and summer blades has not had all fields filled in, for example it has no name.
I believe one of the unfilled fields is causing errors with the doll as the symptoms are identical to when I made the same mistake on the Goodberry item I added.
![image](https://user-images.githubusercontent.com/94767653/193465126-e06271c0-9c2d-46c0-86ab-7be76ba7014a.png)

Easiest way I found to make sure everything is working as it should is that it lets you click the cog for visual options but if there is a problem with a equipped item you cannot.

While it might not be related I did not get the Summer Blade ability until reloading.
Just in case it is important I am not using dark codex.

**Comment by SpencerMycek** [comment] 2022-10-05 11:34
Very interesting
All of the blades should be made identically, and therefore if one has the problem they all do
I'll take a look on my end if you want to see if similar errors are caused by the other blades

**Comment by SpencerMycek** [comment] 2022-10-14 11:04
Fixed in v3.0.1

**Closed as completed by SpencerMycek** 2022-10-14 11:04 UTC
